# Snoopy lighthouse

#preload = /home/agallas/Pictures/Wallpapers/linuxgruv-notext.jpeg
#wallpaper = , /home/agallas/Pictures/Wallpapers/linuxgruv-notext.jpeg

# New syntax
preload = /home/agallas/Pictures/Wallpapers/linuxgruv-notext.jpeg
splash = false

wallpaper {
    monitor = 
    path = /home/agallas/Pictures/Wallpapers/linuxgruv-notext.jpeg
}
