# Snoopy lighthouse

#preload = /home/agallas/Pictures/Wallpapers/buildingsDark.jpg
#wallpaper = , /home/agallas/Pictures/Wallpapers/buildingsDark.jpg

# New syntax
preload = /home/agallas/Pictures/Wallpapers/buildingsDark.jpg
splash = false

wallpaper {
    monitor = 
    path = /home/agallas/Pictures/Wallpapers/buildingsDark.jpg
}
